Bug 1191934 - Remove leftover import
Annoyingly this didn't cause the tests (or flake8) to fail, but on
stage stopped celery from starting:

Traceback (most recent call last):
  ...
  File "/data/www/treeherder.allizom.org/venv/lib/python2.7/site-packages/celery/loaders/base.py", line 273, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
  File "/data/www/treeherder.allizom.org/venv/lib/python2.7/site-packages/celery/loaders/base.py", line 299, in find_related_module
    return importlib.import_module('{0}.{1}'.format(package, related_name))
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/data/www/treeherder.allizom.org/treeherder-service/treeherder/etl/tasks/__init__.py", line 3, in <module>
    from .cleanup_tasks import *
ImportError: No module named cleanup_tasks