Bug 1451518 - Fix SyntaxError in etl/text.py under Python 3
Even though the raw unicode (`ur`) string is in the Python 2 branch
of the conditional, the whole file was parsed, causing a `SyntaxError`
when running Django check under Python 3:

```
...
  File "/home/vagrant/treeherder/treeherder/etl/text.py", line 13
    filter_re = re.compile(ur"([\U00010000-\U0010FFFF])", re.U)  # noqa: E999
                                                       ^
SyntaxError: invalid syntax
```

The `ur` syntax isn't supported under Python 3 (since it was removed
by https://bugs.python.org/issue15096), however we can use the
workaround suggested here:
https://stackoverflow.com/a/33027349