Bug 1277593 - Make FlexibleForeignKey compatible with Django 1.9
Since `related_field` was renamed to `target_field` in:
https://github.com/django/django/pull/4241

Fixes:
AttributeError: 'FlexibleForeignKey' object has no attribute 'related_field'