Bug 1526657 - Make remaining .iteritems() usage Python 3 compatible
Since this usage was added after the others were converted in #3418.

Fixes:
`AttributeError: 'dict' object has no attribute 'iteritems'`