Bug 1504617 - Travis: Explicitly start redis-server
Since the service is no longer started by default in the base Travis
image as of travis-ci/travis-cookbooks#999.

Fixes:

```
ConnectionError: Error 111 connecting to localhost:6379. Connection refused.
```
(eg https://travis-ci.org/mozilla/treeherder/jobs/450605269#L880)