Bug 1133482 - Remove download_logs.py since it's always been broken
Traceback (most recent call last):
  File "./bin/download_logs.py", line 97, in <module>
    download_logs(sys.argv[1])
  File "./bin/download_logs.py", line 74, in download_logs
    logrefs = job["job"]["log_references"]
TypeError: string indices must be integers, not str

And I don't think we have a need for it now anyway.