Bug 1364045 - Don't load '@neutrinojs/jest' in production
Since it's in `devDependencies` so is not installed during deploys.

Fixes:

`Error: Cannot find module '@neutrinojs/jest'`
https://dashboard.heroku.com/apps/treeherder-stage/activity/builds/8228fa8d-0209-43d3-8699-4e6c124b248f