Bug 1118023 - Remove reference to django_browserid.context_processors
Since as of django-browserid v0.10.1 it no longer exists:
http://django-browserid.readthedocs.org/en/latest/user/upgrading.html#to-0-10-1

And was resulting in:
ImportError: No module named context_processors