Revert BugJobMap foreign key part of 4db1aa4 (bug 1367362) (#3236)
Since unfortunately the migration failed on stage due to:
```
IntegrityError: (1452, 'Cannot add or update a child row: a foreign
key constraint fails (`treeherder`.`#sql-1c26_1936a5`, CONSTRAINT
`bug_job_map_bug_id_013db14b_fk_bugscache_id` FOREIGN KEY (`bug_id`)
REFERENCES `bugscache` (`id`))')
```

I believe this is due to the fact that bug numbers are sometimes
manually entered when classifying failures (eg for infra failures),
meaning that not every bug ID in `BugJobMap` is for an intermittent
bug, and so doesn't exist in `Bugscache` (which is currently only
populated with bugs that have the keyword `intermittent-failure`).

This wasn't caught on prototype, since whilst that has some failure
classifications saved, none of them where hand-entered and so all
existed in `Bugscache`, satisfying the new constraint.

I've edited the existing migrations file since in most environments
it won't have already run (I'll fix up prototype/stage by hand). The
non-FK changes have been left as-is, since they are working fine.