Bug 1328985 - Make 0020_remove_project_specific_id a no-op
To fix deployment, since it's currently failing with:
```
django.db.utils.OperationalError: (1091, "Can't DROP
'job_repository_id_project_specific_id_7883a5e8_uniq';
check that column/key exists")
```

We'll just drop the index by hand on dev/stage/prod instead.